import { logger } from "@/lib/logger";

/**
 * Represents the structured response returned by the payment service when creating or querying a payment intent.
 */
export interface PaymentResult {
  /** Unique payment identifier generated by payment-service */
  payment_id: string;
  /** Internal store transaction order ID */
  order_id: string;
  /** Active payment provider processing the transaction */
  provider: "mock" | "pakasir" | "sumopod";
  /** Current state of the payment intent */
  status: "pending" | "paid" | "failed" | "expired";
  /** Base transaction amount */
  amount: number;
  /** ISO 4217 Currency code (e.g. IDR) */
  currency: string;
  /** Primary payment code or QR identifier */
  payment_code: string;
  /** Formatted user-facing payment code representation */
  payment_code_display?: string;
  /** Raw QRIS payload string for rendering QR codes */
  qr_string?: string;
  /** Final calculated total payment amount including fees */
  total_payment?: number;
  /** Gateway service or processing fee */
  fee?: number;
  /** Specific payment method name (e.g. QRIS, VA_BCA) */
  payment_method?: string;
  /** Redirect URL for hosted payment pages */
  payment_url?: string;
  /** Expiration Unix timestamp (seconds) */
  expires_at: number;
  /** ISO 8601 creation timestamp */
  created_at: string;
}

/**
 * Webhook payload structure dispatched by payment-service worker on status changes.
 */
export interface PaymentWebhookPayload {
  /** Triggered lifecycle event type */
  event: "payment.paid" | "payment.failed" | "payment.expired";
  /** Unique idempotent event identifier */
  event_id: string;
  /** Associated payment ID */
  payment_id: string;
  /** Internal store transaction order ID */
  order_id: string;
  /** Updated payment status */
  status: "pending" | "paid" | "failed" | "expired";
  /** Paid transaction amount */
  amount: number;
  /** Currency code */
  currency: string;
  /** Payment reference code */
  payment_code: string;
  /** Timestamp when payment was settled */
  paid_at?: string;
  /** Detailed reason if payment failed */
  failure_reason?: string;
  /** ISO 8601 event emission timestamp */
  timestamp: string;
}

/**
 * Resolves the base URL of the external payment service worker from environment variables.
 * Automatically trims trailing slashes.
 */
export function getPaymentServiceBaseUrl(): string {
  const url = process.env.PAYMENT_SERVICE_URL || process.env.MOCK_PAYMENT_GATEWAY_URL || "";
  return url.replace(/\/+$/, "");
}

/**
 * Retrieves the shared secret key used to verify HMAC SHA-256 signatures from incoming payment webhooks.
 */
export function getPaymentWebhookSecret(): string {
  return (
    process.env.PAYMENT_WEBHOOK_SECRET ||
    process.env.MOCK_PAYMENT_WEBHOOK_SECRET ||
    "dev-sandbox-secret-change-me"
  );
}

/**
 * Resolves the public storefront base URL used for webhook callbacks.
 */
function getSiteBaseUrl(): string {
  return (process.env.NEXT_PUBLIC_SITE_URL || "http://localhost:3000").replace(/\/+$/, "");
}

/**
 * Creates a payment intent via the isolated payment-service worker.
 *
 * @param opts - Payment creation parameters including order details, amount, and return URLs.
 * @returns Resolves to `PaymentResult` object if successfully created, or `null` if unconfigured or failed.
 */
export async function createPayment(opts: {
  orderId: string;
  amount: number;
  description?: string;
  customer?: { name?: string; whatsapp?: string; email?: string };
  expiresInSeconds?: number;
  returnUrl: string;
}): Promise<PaymentResult | null> {
  const base = getPaymentServiceBaseUrl();
  if (!base) return null;

  const callbackUrl = `${getSiteBaseUrl()}/api/webhooks/payment`;

  try {
    const res = await fetch(`${base}/v1/payments`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        order_id: opts.orderId,
        amount: Math.floor(opts.amount),
        currency: "IDR",
        description: opts.description,
        customer: opts.customer,
        expires_in_seconds: opts.expiresInSeconds,
        callback_url: callbackUrl,
        return_url: opts.returnUrl,
      }),
      cache: "no-store",
    });

    if (!res.ok) {
      const body = await res.text().catch(() => "");
      logger.warn("payment create failed", {
        orderId: opts.orderId,
        status: res.status,
        body,
      });
      return null;
    }

    const json = (await res.json()) as { success: boolean; data: PaymentResult };
    if (!json?.success || !json.data) return null;

    return json.data;
  } catch (error) {
    logger.warn("payment create threw", { orderId: opts.orderId, error });
    return null;
  }
}

/**
 * Validates the HMAC-SHA256 signature of incoming payment service webhook requests.
 * Uses constant-time comparison to prevent timing attacks.
 *
 * @param rawBody - Raw request body payload as string.
 * @param signature - Signature string sent in HTTP header (`x-payment-signature` or `x-mock-signature`).
 * @returns Promise resolving to `true` if signature matches, `false` otherwise.
 */
export async function verifyPaymentWebhookSignature(
  rawBody: string,
  signature: string | null | undefined,
): Promise<boolean> {
  if (!signature || !rawBody) return false;
  const secret = getPaymentWebhookSecret();

  const encoder = new TextEncoder();
  const key = await crypto.subtle.importKey(
    "raw",
    encoder.encode(secret),
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"],
  );
  const sig = await crypto.subtle.sign("HMAC", key, encoder.encode(rawBody));

  const expected = Array.from(new Uint8Array(sig))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");

  const actual = signature.toLowerCase();
  if (expected.length !== actual.length) return false;

  let diff = 0;
  for (let i = 0; i < expected.length; i++) {
    diff |= expected.charCodeAt(i) ^ actual.charCodeAt(i);
  }
  return diff === 0;
}
