// ============================================================================
// DEFAULT SEED & FALLBACK DATA UNTUK FERYSHOP
// Digunakan sebagai fallback jika Supabase belum dikonfigurasi atau tabel masih kosong
// ============================================================================

export const seedCategories = [
  {
    id: 1,
    title: "Mobile Games",
    logo: "/images/ml.png",
    game: "Mobile Games",
    sortOrder: 1,
    isActive: true,
  },
  {
    id: 2,
    title: "PC Games",
    logo: "/images/val.png",
    game: "PC Games",
    sortOrder: 2,
    isActive: true,
  },
  {
    id: 3,
    title: "Voucher",
    logo: "/images/steam.png",
    game: "Voucher",
    sortOrder: 3,
    isActive: true,
  },
  {
    id: 4,
    title: "Entertainment",
    logo: "/images/netflix.png",
    game: "Entertainment",
    sortOrder: 4,
    isActive: true,
  },
];

export const seedGames = [
  {
    id: 1,
    title: "Mobile Legends: Bang Bang",
    slug: "mobile-legends",
    image:
      "https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=400&auto=format&fit=crop",
    banner:
      "https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=1200&auto=format&fit=crop",
    logo: "https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=100&auto=format&fit=crop",
    developers: "Moonton",
    categoryId: 1,
    description:
      "Top up Diamond Mobile Legends resmi 100% legal, murah, dan instan masuk ke akun Anda dalam hitungan detik.",
    instructions: {
      title: "Cara Top Up Mobile Legends",
      steps: [
        "Masukkan User ID dan Zone ID Anda (Contoh: 12345678 (1234))",
        "Pilih nominal Diamond atau Pass yang ingin dibeli",
        "Pilih metode pembayaran yang Anda inginkan",
        "Selesaikan pembayaran dan Diamond akan otomatis masuk ke akun Anda",
      ],
      required_inputs: ["id", "server"],
      input_fields: [
        { name: "id", label: "User ID", placeholder: "Masukkan User ID", type: "text" },
        { name: "server", label: "Server ID", placeholder: "Masukkan Server ID", type: "text" },
      ],
      code_validation_nickname: "ml",
      status_validation_nickname: "yes",
    },
    isPopular: true,
    isActive: true,
    sortOrder: 1,
  },
  {
    id: 2,
    title: "Free Fire",
    slug: "free-fire",
    image:
      "https://images.unsplash.com/photo-1511512578047-dfb367046420?q=80&w=400&auto=format&fit=crop",
    banner:
      "https://images.unsplash.com/photo-1511512578047-dfb367046420?q=80&w=1200&auto=format&fit=crop",
    logo: "https://images.unsplash.com/photo-1511512578047-dfb367046420?q=80&w=100&auto=format&fit=crop",
    developers: "Garena",
    categoryId: 1,
    description: "Top up Diamond Free Fire Garena termurah dan tercepat langsung proses 24 jam.",
    instructions: {
      title: "Cara Top Up Free Fire",
      steps: [
        "Masukkan Player ID Free Fire Anda",
        "Pilih nominal Diamond yang diinginkan",
        "Pilih metode pembayaran",
        "Selesaikan pembayaran dan Diamond akan langsung bertambah",
      ],
      required_inputs: ["id"],
      input_fields: [
        { name: "id", label: "User ID", placeholder: "Masukkan User ID", type: "text" },
      ],
    },
    isPopular: true,
    isActive: true,
    sortOrder: 2,
  },
  {
    id: 3,
    title: "PUBG Mobile",
    slug: "pubg-mobile",
    image:
      "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?q=80&w=400&auto=format&fit=crop",
    banner:
      "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?q=80&w=1200&auto=format&fit=crop",
    logo: "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?q=80&w=100&auto=format&fit=crop",
    developers: "Tencent / Level Infinite",
    categoryId: 1,
    description: "Top up UC PUBG Mobile legal resmi aman dengan berbagai nominal.",
    instructions: {
      title: "Cara Top Up PUBG Mobile",
      steps: [
        "Masukkan Player ID PUBG Mobile Anda",
        "Pilih nominal UC",
        "Pilih metode pembayaran dan selesaikan transaksi",
      ],
      required_inputs: ["id"],
      input_fields: [
        { name: "id", label: "User ID", placeholder: "Masukkan User ID", type: "text" },
      ],
      warning_text:
        "ID Indonesia bisa membeli produk Global, tapi ID Global tidak bisa membeli produk Indo (khusus Top Up Instant).",
    },
    isPopular: true,
    isActive: true,
    sortOrder: 3,
  },
  {
    id: 4,
    title: "Valorant",
    slug: "valorant",
    image:
      "https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=400&auto=format&fit=crop",
    banner:
      "https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=1200&auto=format&fit=crop",
    logo: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=100&auto=format&fit=crop",
    developers: "Riot Games",
    categoryId: 2,
    description: "Beli Valorant Points (VP) resmi Riot Games dengan cepat dan harga terjangkau.",
    instructions: {
      title: "Cara Top Up Valorant",
      steps: [
        "Masukkan Riot ID Anda (Contoh: Username#TAG)",
        "Pilih nominal Valorant Points",
        "Pilih pembayaran dan selesaikan",
      ],
      required_inputs: ["id"],
      input_fields: [
        { name: "id", label: "Riot ID (Nama#Tag)", placeholder: "Contoh: tnaka#sea", type: "text" },
      ],
    },
    isPopular: true,
    isActive: true,
    sortOrder: 4,
  },
  {
    id: 5,
    title: "Genshin Impact",
    slug: "genshin-impact",
    image:
      "https://images.unsplash.com/photo-1578632767115-351597cf2477?q=80&w=400&auto=format&fit=crop",
    banner:
      "https://images.unsplash.com/photo-1578632767115-351597cf2477?q=80&w=1200&auto=format&fit=crop",
    logo: "https://images.unsplash.com/photo-1578632767115-351597cf2477?q=80&w=100&auto=format&fit=crop",
    developers: "HoYoverse",
    categoryId: 1,
    description:
      "Top up Genesis Crystals & Blessing of the Welkin Moon Genshin Impact resmi dan instan.",
    instructions: {
      title: "Cara Top Up Genshin Impact",
      steps: [
        "Masukkan User ID (UID) dan Server Genshin Impact Anda",
        "Pilih nominal Genesis Crystals atau Welkin Moon",
        "Pilih metode pembayaran dan selesaikan transaksi",
      ],
      required_inputs: ["id", "server"],
      input_fields: [
        { name: "id", label: "UID", placeholder: "Masukkan UID", type: "text" },
        { name: "server", label: "Server", placeholder: "Pilih Server", type: "select" },
      ],
      options: [
        { value: "Asia", label: "Asia" },
        { value: "America", label: "America" },
        { value: "Europe", label: "Europe" },
        { value: "TW_HK_MO", label: "TW, HK, MO" },
      ],
    },
    isPopular: true,
    isActive: true,
    sortOrder: 5,
  },
  {
    id: 6,
    title: "Roblox",
    slug: "roblox",
    image:
      "https://images.unsplash.com/photo-1614680376593-902f749f705d?q=80&w=400&auto=format&fit=crop",
    banner:
      "https://images.unsplash.com/photo-1614680376593-902f749f705d?q=80&w=1200&auto=format&fit=crop",
    logo: "https://images.unsplash.com/photo-1614680376593-902f749f705d?q=80&w=100&auto=format&fit=crop",
    developers: "Roblox Corporation",
    categoryId: 1,
    description: "Top up Robux resmi cepat dan murah untuk akun Roblox kamu.",
    instructions: {
      title: "Cara Top Up Roblox",
      steps: [
        "Masukkan Username/Email, Password, dan 3 Code Backup Anda",
        "Pilih nominal Robux yang diinginkan",
        "Matikan Verify-to-Login (V2L) dan Passkey sebelum order",
        "Selesaikan pembayaran (Proses manual estimasi 10-180 menit)",
      ],
      required_inputs: ["email", "password", "code_backup"],
      input_fields: [
        {
          name: "email",
          label: "Username / Email",
          placeholder: "Masukkan Username/Email",
          type: "text",
        },
        {
          name: "password",
          label: "Password Akun",
          placeholder: "Masukkan Password",
          type: "password",
        },
        {
          name: "code_backup",
          label: "3 Code Backup",
          placeholder: "Masukkan 3 Code Backup",
          type: "text",
        },
      ],
      warning_text:
        "Top up manual (06.00–21.59 WIB, estimasi 10–180 menit). Wajib mematikan Verify-to-Login (V2L) dan Passkey sebelum order.",
    },
    isPopular: true,
    isActive: true,
    sortOrder: 6,
  },
  {
    id: 7,
    title: "Honor of Kings",
    slug: "honor-of-kings",
    image:
      "https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=400&auto=format&fit=crop",
    banner:
      "https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=1200&auto=format&fit=crop",
    logo: "https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=100&auto=format&fit=crop",
    developers: "Level Infinite",
    categoryId: 1,
    description: "Top up Tokens & Weekly Card Honor of Kings murah dan cepat.",
    instructions: {
      title: "Cara Top Up Honor of Kings",
      steps: [
        "Masukkan UID Honor of Kings Anda",
        "Pilih nominal Tokens atau Card",
        "Selesaikan pembayaran",
      ],
      required_inputs: ["id"],
      input_fields: [{ name: "id", label: "UID", placeholder: "Masukkan UID", type: "text" }],
    },
    isPopular: true,
    isActive: true,
    sortOrder: 7,
  },
  {
    id: 8,
    title: "Call of Duty: Mobile",
    slug: "call-of-duty-mobile",
    image:
      "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?q=80&w=400&auto=format&fit=crop",
    banner:
      "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?q=80&w=1200&auto=format&fit=crop",
    logo: "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?q=80&w=100&auto=format&fit=crop",
    developers: "Garena",
    categoryId: 1,
    description: "Top up CP Call of Duty Mobile resmi dan terpercaya.",
    instructions: {
      title: "Cara Top Up Call of Duty Mobile",
      steps: ["Masukkan Player ID CODM Anda", "Pilih nominal CP", "Selesaikan pembayaran"],
      required_inputs: ["id"],
      input_fields: [
        { name: "id", label: "Player ID", placeholder: "Masukkan Player ID", type: "text" },
      ],
      warning_text:
        "Akun yang terhubung (bind) ke Garena otomatis tidak didukung (akan gagal top up).",
    },
    isPopular: false,
    isActive: true,
    sortOrder: 8,
  },
];

export const seedProducts: Record<string, any[]> = {
  "mobile-legends": [
    {
      id: "ML-86",
      title: "86 Diamonds (78 + 8 Bonus)",
      selling_price: 20000,
      selling_price_gold: 19500,
      selling_price_platinum: 19000,
      promo_price: null,
      is_active: true,
    },
    {
      id: "ML-172",
      title: "172 Diamonds (156 + 16 Bonus)",
      selling_price: 40000,
      selling_price_gold: 39000,
      selling_price_platinum: 38000,
      promo_price: null,
      is_active: true,
    },
    {
      id: "ML-257",
      title: "257 Diamonds (234 + 23 Bonus)",
      selling_price: 60000,
      selling_price_gold: 58500,
      selling_price_platinum: 57000,
      promo_price: null,
      is_active: true,
    },
    {
      id: "ML-344",
      title: "344 Diamonds (312 + 32 Bonus)",
      selling_price: 80000,
      selling_price_gold: 78000,
      selling_price_platinum: 76000,
      promo_price: null,
      is_active: true,
    },
    {
      id: "ML-706",
      title: "706 Diamonds (625 + 81 Bonus)",
      selling_price: 165000,
      selling_price_gold: 162000,
      selling_price_platinum: 159000,
      promo_price: null,
      is_active: true,
    },
    {
      id: "ML-1412",
      title: "1412 Diamonds (1250 + 162 Bonus)",
      selling_price: 330000,
      selling_price_gold: 324000,
      selling_price_platinum: 318000,
      promo_price: null,
      is_active: true,
    },
    {
      id: "ML-WDP",
      title: "Weekly Diamond Pass (WDP)",
      selling_price: 28000,
      selling_price_gold: 27500,
      selling_price_platinum: 27000,
      promo_price: 26500,
      is_active: true,
    },
    {
      id: "ML-TWILIGHT",
      title: "Twilight Pass",
      selling_price: 145000,
      selling_price_gold: 142000,
      selling_price_platinum: 139000,
      promo_price: null,
      is_active: true,
    },
  ],
  "free-fire": [
    {
      id: "FF-5",
      title: "5 Diamonds",
      selling_price: 1500,
      selling_price_gold: 1400,
      selling_price_platinum: 1300,
      promo_price: null,
      is_active: true,
    },
    {
      id: "FF-12",
      title: "12 Diamonds",
      selling_price: 2500,
      selling_price_gold: 2400,
      selling_price_platinum: 2300,
      promo_price: null,
      is_active: true,
    },
    {
      id: "FF-50",
      title: "50 Diamonds",
      selling_price: 8000,
      selling_price_gold: 7800,
      selling_price_platinum: 7500,
      promo_price: null,
      is_active: true,
    },
    {
      id: "FF-70",
      title: "70 Diamonds",
      selling_price: 10000,
      selling_price_gold: 9800,
      selling_price_platinum: 9500,
      promo_price: null,
      is_active: true,
    },
    {
      id: "FF-140",
      title: "140 Diamonds",
      selling_price: 19500,
      selling_price_gold: 19000,
      selling_price_platinum: 18500,
      promo_price: null,
      is_active: true,
    },
    {
      id: "FF-355",
      title: "355 Diamonds",
      selling_price: 48500,
      selling_price_gold: 47500,
      selling_price_platinum: 46500,
      promo_price: null,
      is_active: true,
    },
    {
      id: "FF-720",
      title: "720 Diamonds",
      selling_price: 96500,
      selling_price_gold: 95000,
      selling_price_platinum: 93500,
      promo_price: null,
      is_active: true,
    },
    {
      id: "FF-1440",
      title: "1440 Diamonds",
      selling_price: 192000,
      selling_price_gold: 189000,
      selling_price_platinum: 186000,
      promo_price: null,
      is_active: true,
    },
    {
      id: "FF-WM",
      title: "Membership Mingguan (Weekly)",
      selling_price: 33000,
      selling_price_gold: 32000,
      selling_price_platinum: 31000,
      promo_price: null,
      is_active: true,
    },
    {
      id: "FF-MM",
      title: "Membership Bulanan (Monthly)",
      selling_price: 165000,
      selling_price_gold: 161000,
      selling_price_platinum: 157000,
      promo_price: null,
      is_active: true,
    },
  ],
  "pubg-mobile": [
    {
      id: "PUBG-60",
      title: "60 UC",
      selling_price: 15000,
      selling_price_gold: 14700,
      selling_price_platinum: 14400,
      promo_price: null,
      is_active: true,
    },
    {
      id: "PUBG-325",
      title: "325 UC (300 + 25 Bonus)",
      selling_price: 74500,
      selling_price_gold: 73000,
      selling_price_platinum: 71500,
      promo_price: null,
      is_active: true,
    },
    {
      id: "PUBG-660",
      title: "660 UC (600 + 60 Bonus)",
      selling_price: 149000,
      selling_price_gold: 146000,
      selling_price_platinum: 143000,
      promo_price: null,
      is_active: true,
    },
    {
      id: "PUBG-1800",
      title: "1800 UC (1500 + 300 Bonus)",
      selling_price: 399000,
      selling_price_gold: 392000,
      selling_price_platinum: 385000,
      promo_price: null,
      is_active: true,
    },
    {
      id: "PUBG-3850",
      title: "3850 UC (3000 + 850 Bonus)",
      selling_price: 799000,
      selling_price_gold: 785000,
      selling_price_platinum: 770000,
      promo_price: null,
      is_active: true,
    },
  ],
  valorant: [
    {
      id: "VAL-300",
      title: "300 Valorant Points",
      selling_price: 40000,
      selling_price_gold: 39000,
      selling_price_platinum: 38000,
      promo_price: null,
      is_active: true,
    },
    {
      id: "VAL-625",
      title: "625 Valorant Points",
      selling_price: 80000,
      selling_price_gold: 78000,
      selling_price_platinum: 76000,
      promo_price: null,
      is_active: true,
    },
    {
      id: "VAL-1125",
      title: "1125 Valorant Points",
      selling_price: 140000,
      selling_price_gold: 137000,
      selling_price_platinum: 134000,
      promo_price: null,
      is_active: true,
    },
    {
      id: "VAL-1650",
      title: "1650 Valorant Points",
      selling_price: 200000,
      selling_price_gold: 196000,
      selling_price_platinum: 192000,
      promo_price: null,
      is_active: true,
    },
    {
      id: "VAL-2400",
      title: "2400 Valorant Points",
      selling_price: 280000,
      selling_price_gold: 274000,
      selling_price_platinum: 268000,
      promo_price: null,
      is_active: true,
    },
    {
      id: "VAL-5800",
      title: "5800 Valorant Points",
      selling_price: 650000,
      selling_price_gold: 637000,
      selling_price_platinum: 624000,
      promo_price: null,
      is_active: true,
    },
  ],
  "genshin-impact": [
    {
      id: "GI-60",
      title: "60 Genesis Crystals",
      selling_price: 16000,
      selling_price_gold: 15500,
      selling_price_platinum: 15000,
      promo_price: null,
      is_active: true,
    },
    {
      id: "GI-330",
      title: "330 Genesis Crystals (300 + 30 Bonus)",
      selling_price: 79000,
      selling_price_gold: 77000,
      selling_price_platinum: 75000,
      promo_price: null,
      is_active: true,
    },
    {
      id: "GI-1090",
      title: "1090 Genesis Crystals (980 + 110 Bonus)",
      selling_price: 249000,
      selling_price_gold: 244000,
      selling_price_platinum: 239000,
      promo_price: null,
      is_active: true,
    },
    {
      id: "GI-2240",
      title: "2240 Genesis Crystals (1980 + 260 Bonus)",
      selling_price: 479000,
      selling_price_gold: 469000,
      selling_price_platinum: 459000,
      promo_price: null,
      is_active: true,
    },
    {
      id: "GI-3880",
      title: "3880 Genesis Crystals (3280 + 600 Bonus)",
      selling_price: 799000,
      selling_price_gold: 783000,
      selling_price_platinum: 767000,
      promo_price: null,
      is_active: true,
    },
    {
      id: "GI-8080",
      title: "8080 Genesis Crystals (6480 + 1600 Bonus)",
      selling_price: 1599000,
      selling_price_gold: 1567000,
      selling_price_platinum: 1535000,
      promo_price: null,
      is_active: true,
    },
    {
      id: "GI-WELKIN",
      title: "Blessing of the Welkin Moon",
      selling_price: 79000,
      selling_price_gold: 77000,
      selling_price_platinum: 75000,
      promo_price: null,
      is_active: true,
    },
  ],
  roblox: [
    {
      id: "RBX-80",
      title: "80 Robux",
      selling_price: 16000,
      selling_price_gold: 15500,
      selling_price_platinum: 15000,
      promo_price: null,
      is_active: true,
    },
    {
      id: "RBX-400",
      title: "400 Robux",
      selling_price: 75000,
      selling_price_gold: 73000,
      selling_price_platinum: 71000,
      promo_price: null,
      is_active: true,
    },
    {
      id: "RBX-800",
      title: "800 Robux",
      selling_price: 150000,
      selling_price_gold: 146000,
      selling_price_platinum: 142000,
      promo_price: null,
      is_active: true,
    },
    {
      id: "RBX-1700",
      title: "1700 Robux",
      selling_price: 310000,
      selling_price_gold: 302000,
      selling_price_platinum: 294000,
      promo_price: null,
      is_active: true,
    },
    {
      id: "RBX-4500",
      title: "4500 Robux",
      selling_price: 790000,
      selling_price_gold: 770000,
      selling_price_platinum: 750000,
      promo_price: null,
      is_active: true,
    },
    {
      id: "RBX-10000",
      title: "10000 Robux",
      selling_price: 1690000,
      selling_price_gold: 1650000,
      selling_price_platinum: 1610000,
      promo_price: null,
      is_active: true,
    },
  ],
  "honor-of-kings": [
    {
      id: "HOK-80",
      title: "80 Tokens",
      selling_price: 16000,
      selling_price_gold: 15500,
      selling_price_platinum: 15000,
      promo_price: null,
      is_active: true,
    },
    {
      id: "HOK-240",
      title: "240 Tokens",
      selling_price: 48000,
      selling_price_gold: 46800,
      selling_price_platinum: 45600,
      promo_price: null,
      is_active: true,
    },
    {
      id: "HOK-400",
      title: "400 Tokens",
      selling_price: 79000,
      selling_price_gold: 77000,
      selling_price_platinum: 75000,
      promo_price: null,
      is_active: true,
    },
    {
      id: "HOK-800",
      title: "800 Tokens",
      selling_price: 158000,
      selling_price_gold: 154000,
      selling_price_platinum: 150000,
      promo_price: null,
      is_active: true,
    },
    {
      id: "HOK-WEEKLY",
      title: "Weekly Card",
      selling_price: 16000,
      selling_price_gold: 15500,
      selling_price_platinum: 15000,
      promo_price: null,
      is_active: true,
    },
    {
      id: "HOK-WEEKLY-PLUS",
      title: "Weekly Card Plus",
      selling_price: 48000,
      selling_price_gold: 46800,
      selling_price_platinum: 45600,
      promo_price: null,
      is_active: true,
    },
  ],
  "call-of-duty-mobile": [
    {
      id: "CODM-31",
      title: "31 CP",
      selling_price: 5000,
      selling_price_gold: 4800,
      selling_price_platinum: 4600,
      promo_price: null,
      is_active: true,
    },
    {
      id: "CODM-62",
      title: "62 CP",
      selling_price: 10000,
      selling_price_gold: 9700,
      selling_price_platinum: 9400,
      promo_price: null,
      is_active: true,
    },
    {
      id: "CODM-127",
      title: "127 CP",
      selling_price: 20000,
      selling_price_gold: 19500,
      selling_price_platinum: 19000,
      promo_price: null,
      is_active: true,
    },
    {
      id: "CODM-320",
      title: "320 CP",
      selling_price: 50000,
      selling_price_gold: 48800,
      selling_price_platinum: 47600,
      promo_price: null,
      is_active: true,
    },
    {
      id: "CODM-645",
      title: "645 CP",
      selling_price: 100000,
      selling_price_gold: 97500,
      selling_price_platinum: 95000,
      promo_price: null,
      is_active: true,
    },
  ],
};

export const seedPaymentMethods = [
  {
    id: "qris",
    name: "QRIS (All Bank & E-Wallet)",
    images: "https://upload.wikimedia.org/wikipedia/commons/a/a2/Logo_QRIS.svg",
    payment_id: "QRIS",
    minimum_amount: 1000,
    maximum_amount: 10000000,
    fee: 0,
    fee_percent: 0.7,
    type: "qris",
    status: "active",
    group: "QRIS & E-Wallet",
    instructions: [
      {
        title: "Cara Bayar dengan QRIS",
        steps: [
          "Buka aplikasi E-Wallet (GoPay, OVO, DANA, ShopeePay) atau Mobile Banking Anda",
          "Pilih menu Scan / Bayar",
          "Scan QR Code yang muncul di layar",
          "Periksa detail pembayaran dan masukkan PIN Anda",
        ],
      },
    ],
  },
  {
    id: "gopay",
    name: "GoPay",
    images: "https://upload.wikimedia.org/wikipedia/commons/8/86/Gopay_logo.svg",
    payment_id: "GOPAY",
    minimum_amount: 1000,
    maximum_amount: 2000000,
    fee: 1000,
    fee_percent: 1.5,
    type: "e-wallet",
    status: "inactive",
    group: "QRIS & E-Wallet",
  },
];

export const seedSliders = [
  {
    id: 1,
    title: "Top Up Mobile Legends Instant & Termurah",
    image:
      "https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=1200&auto=format&fit=crop",
    url: "/order/mobile-legends",
    isActive: true,
  },
  {
    id: 2,
    title: "Diskon Spesial Valorant Points",
    image:
      "https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=1200&auto=format&fit=crop",
    url: "/order/valorant",
    isActive: true,
  },
];

export const seedArticles = [
  {
    id: 1,
    title: "Cara Top Up Mobile Legends Aman dan Cepat di Feryshop",
    slug: "cara-top-up-mobile-legends-aman-cepat",
    image:
      "https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=1200&auto=format&fit=crop",
    thumbnail:
      "https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=1200&auto=format&fit=crop",
    excerpt:
      "Panduan memilih nominal diamond MLBB, mengisi User ID dan Zone ID, sampai pembayaran selesai tanpa salah kirim.",
    content:
      "<p>Top up Mobile Legends di Feryshop dibuat sederhana untuk pemain yang ingin proses cepat tanpa ribet. Siapkan User ID dan Zone ID, pilih nominal diamond atau Weekly Diamond Pass, lalu lanjutkan ke metode pembayaran yang tersedia.</p>",
    author: "Admin Feryshop",
    views: 1840,
    created_at: "2026-07-20T10:00:00Z",
    published_at: "2026-07-20T10:00:00Z",
    category: { id: 1, title: "Panduan", slug: "panduan" },
  },
];

export const seedSettings = {
  site_name: "Feryshop",
  site_title: "Feryshop - Marketplace Akun Game Sultan & Top Up",
  site_description:
    "Platform marketplace akun game Sultan dan layanan top up game resmi termurah dan otomatis 24 jam di Indonesia.",
  logo: "/logo-2.png",
  favicon: "/favicon.ico",
  footer_text: "Made in Feryshop",
  social_facebook: "https://facebook.com",
  social_instagram: "https://instagram.com",
  social_whatsapp: "https://wa.me/628123456789",
  enable_account_api_settings: false,
};
