// ============================================================================
// DEFAULT SEED & FALLBACK DATA UNTUK FERYSHOP
// Digunakan sebagai fallback jika Supabase belum dikonfigurasi atau tabel masih kosong
// ====================================================================

export const seedCategories = [
  { id: 1, title: 'Mobile Games', logo: '/images/ml.png', game: 'Mobile Games', sortOrder: 1, isActive: true },
  { id: 2, title: 'PC Games', logo: '/images/val.png', game: 'PC Games', sortOrder: 2, isActive: true },
  { id: 3, title: 'Voucher', logo: '/images/steam.png', game: 'Voucher', sortOrder: 3, isActive: true },
  { id: 4, title: 'Entertainment', logo: '/images/netflix.png', game: 'Entertainment', sortOrder: 4, isActive: true },
];

export const seedGames = [
  {
    id: 1,
    title: 'Mobile Legends: Bang Bang',
    slug: 'mobile-legends',
    image: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=400&auto=format&fit=crop',
    banner: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=1200&auto=format&fit=crop',
    logo: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=100&auto=format&fit=crop',
    developers: 'Moonton',
    categoryId: 1,
    description: 'Top up Diamond Mobile Legends resmi 100% legal, murah, dan instan masuk ke akun Anda dalam hitungan detik.',
    instructions: {
      title: 'Cara Top Up Mobile Legends',
      steps: [
        'Masukkan User ID dan Zone ID Anda (Contoh: 12345678 (1234))',
        'Pilih nominal Diamond atau Pass yang ingin dibeli',
        'Pilih metode pembayaran yang Anda inginkan',
        'Selesaikan pembayaran dan Diamond akan otomatis masuk ke akun Anda',
      ],
      fields: [
        { name: 'id', label: 'User ID', placeholder: 'Masukkan User ID', type: 'text', required: true },
        { name: 'server', label: 'Zone ID', placeholder: 'Masukkan Zone ID (1234)', type: 'text', required: true },
      ],
    },
    isPopular: true,
    isActive: true,
    sortOrder: 1,
  },
  {
    id: 2,
    title: 'Free Fire',
    slug: 'free-fire',
    image: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?q=80&w=400&auto=format&fit=crop',
    banner: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?q=80&w=1200&auto=format&fit=crop',
    logo: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?q=80&w=100&auto=format&fit=crop',
    developers: 'Garena',
    categoryId: 1,
    description: 'Top up Diamond Free Fire Garena termurah dan tercepat langsung proses 24 jam.',
    instructions: {
      title: 'Cara Top Up Free Fire',
      steps: [
        'Masukkan Player ID Free Fire Anda',
        'Pilih nominal Diamond yang diinginkan',
        'Pilih metode pembayaran',
        'Selesaikan pembayaran dan Diamond akan langsung bertambah',
      ],
      fields: [
        { name: 'id', label: 'Player ID', placeholder: 'Masukkan Player ID', type: 'text', required: true },
      ],
    },
    isPopular: true,
    isActive: true,
    sortOrder: 2,
  },
  {
    id: 3,
    title: 'PUBG Mobile',
    slug: 'pubg-mobile',
    image: 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?q=80&w=400&auto=format&fit=crop',
    banner: 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?q=80&w=1200&auto=format&fit=crop',
    logo: 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?q=80&w=100&auto=format&fit=crop',
    developers: 'Tencent / Level Infinite',
    categoryId: 1,
    description: 'Top up UC PUBG Mobile legal resmi aman dengan berbagai nominal.',
    instructions: {
      title: 'Cara Top Up PUBG Mobile',
      steps: [
        'Masukkan Player ID PUBG Mobile Anda',
        'Pilih nominal UC',
        'Pilih metode pembayaran dan selesaikan transaksi',
      ],
      fields: [
        { name: 'id', label: 'Player ID', placeholder: 'Masukkan Player ID', type: 'text', required: true },
      ],
    },
    isPopular: true,
    isActive: true,
    sortOrder: 3,
  },
  {
    id: 4,
    title: 'Valorant',
    slug: 'valorant',
    image: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=400&auto=format&fit=crop',
    banner: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=1200&auto=format&fit=crop',
    logo: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=100&auto=format&fit=crop',
    developers: 'Riot Games',
    categoryId: 2,
    description: 'Beli Valorant Points (VP) resmi Riot Games dengan cepat dan harga terjangkau.',
    instructions: {
      title: 'Cara Top Up Valorant',
      steps: [
        'Masukkan Riot ID Anda (Contoh: Username#TAG)',
        'Pilih nominal Valorant Points',
        'Pilih pembayaran dan selesaikan',
      ],
      fields: [
        { name: 'id', label: 'Riot ID', placeholder: 'Username#TAG', type: 'text', required: true },
      ],
    },
    isPopular: true,
    isActive: true,
    sortOrder: 4,
  },
];

export const seedProducts: Record<string, any[]> = {
  'mobile-legends': [
    { id: 'ML-86', title: '86 Diamonds (78 + 8 Bonus)', selling_price: 23500, selling_price_gold: 23000, selling_price_platinum: 22500, promo_price: 22000, is_active: true },
    { id: 'ML-172', title: '172 Diamonds (156 + 16 Bonus)', selling_price: 46500, selling_price_gold: 45500, selling_price_platinum: 44500, promo_price: null, is_active: true },
    { id: 'ML-257', title: '257 Diamonds (234 + 23 Bonus)', selling_price: 69000, selling_price_gold: 68000, selling_price_platinum: 67000, promo_price: null, is_active: true },
    { id: 'ML-344', title: '344 Diamonds (312 + 32 Bonus)', selling_price: 92000, selling_price_gold: 90500, selling_price_platinum: 89000, promo_price: null, is_active: true },
    { id: 'ML-706', title: '706 Diamonds (625 + 81 Bonus)', selling_price: 185000, selling_price_gold: 182000, selling_price_platinum: 179000, promo_price: null, is_active: true },
    { id: 'ML-WDP', title: 'Weekly Diamond Pass (WDP)', selling_price: 28500, selling_price_gold: 28000, selling_price_platinum: 27500, promo_price: 27000, is_active: true },
  ],
  'free-fire': [
    { id: 'FF-70', title: '70 Diamonds', selling_price: 10000, selling_price_gold: 9800, selling_price_platinum: 9500, promo_price: null, is_active: true },
    { id: 'FF-140', title: '140 Diamonds', selling_price: 19500, selling_price_gold: 19000, selling_price_platinum: 18500, promo_price: null, is_active: true },
    { id: 'FF-355', title: '355 Diamonds', selling_price: 48500, selling_price_gold: 47500, selling_price_platinum: 46500, promo_price: null, is_active: true },
    { id: 'FF-720', title: '720 Diamonds', selling_price: 96500, selling_price_gold: 95000, selling_price_platinum: 93500, promo_price: null, is_active: true },
  ],
  'pubg-mobile': [
    { id: 'PUBG-60', title: '60 UC', selling_price: 15000, selling_price_gold: 14700, selling_price_platinum: 14400, promo_price: null, is_active: true },
    { id: 'PUBG-325', title: '325 UC (300 + 25 Bonus)', selling_price: 74500, selling_price_gold: 73000, selling_price_platinum: 71500, promo_price: null, is_active: true },
    { id: 'PUBG-660', title: '660 UC (600 + 60 Bonus)', selling_price: 149000, selling_price_gold: 146000, selling_price_platinum: 143000, promo_price: null, is_active: true },
  ],
  'valorant': [
    { id: 'VAL-300', title: '300 Points', selling_price: 40000, selling_price_gold: 39000, selling_price_platinum: 38000, promo_price: null, is_active: true },
    { id: 'VAL-625', title: '625 Points', selling_price: 80000, selling_price_gold: 78000, selling_price_platinum: 76000, promo_price: null, is_active: true },
    { id: 'VAL-1125', title: '1125 Points', selling_price: 140000, selling_price_gold: 137000, selling_price_platinum: 134000, promo_price: null, is_active: true },
  ],
};

export const seedPaymentMethods = [
  {
    id: 'qris',
    name: 'QRIS (All Bank & E-Wallet)',
    images: 'https://upload.wikimedia.org/wikipedia/commons/a/a2/Logo_QRIS.svg',
    payment_id: 'QRIS',
    minimum_amount: 1000,
    maximum_amount: 10000000,
    fee: 0,
    fee_percent: 0.7,
    type: 'qris',
    status: 'active',
    group: 'QRIS & E-Wallet',
    instructions: [
      { title: 'Cara Bayar dengan QRIS', steps: ['Buka aplikasi E-Wallet (GoPay, OVO, DANA, ShopeePay) atau Mobile Banking Anda', 'Pilih menu Scan / Bayar', 'Scan QR Code yang muncul di layar', 'Periksa detail pembayaran dan masukkan PIN Anda'] },
    ],
  },
  {
    id: 'gopay',
    name: 'GoPay',
    images: 'https://upload.wikimedia.org/wikipedia/commons/8/86/Gopay_logo.svg',
    payment_id: 'GOPAY',
    minimum_amount: 1000,
    maximum_amount: 2000000,
    fee: 1000,
    fee_percent: 1.5,
    type: 'e-wallet',
    status: 'active',
    group: 'QRIS & E-Wallet',
    instructions: [
      { title: 'Cara Bayar via GoPay', steps: ['Klik tombol Bayar Sekarang untuk membuka aplikasi Gojek/GoPay', 'Konfirmasi nominal pembayaran', 'Masukkan PIN GoPay Anda'] },
    ],
  },
  {
    id: 'va_bca',
    name: 'BCA Virtual Account',
    images: 'https://upload.wikimedia.org/wikipedia/commons/5/5c/Bank_Central_Asia.svg',
    payment_id: 'VA_BCA',
    minimum_amount: 10000,
    maximum_amount: 50000000,
    fee: 4000,
    fee_percent: 0,
    type: 'va',
    status: 'active',
    group: 'Virtual Account Bank',
    instructions: [
      { title: 'm-BCA (BCA mobile)', steps: ['Buka BCA mobile dan pilih m-BCA', 'Pilih menu m-Transfer > BCA Virtual Account', 'Masukkan nomor Virtual Account yang tertera', 'Periksa nominal pembayaran dan masukkan PIN m-BCA'] },
    ],
  },
  {
    id: 'va_mandiri',
    name: 'Mandiri Virtual Account',
    images: 'https://upload.wikimedia.org/wikipedia/commons/a/ad/Bank_Mandiri_logo_2016.svg',
    payment_id: 'VA_MANDIRI',
    minimum_amount: 10000,
    maximum_amount: 50000000,
    fee: 4000,
    fee_percent: 0,
    type: 'va',
    status: 'active',
    group: 'Virtual Account Bank',
    instructions: [
      { title: 'Livin by Mandiri', steps: ['Buka aplikasi Livin by Mandiri', 'Pilih menu Bayar > Multi Payment', 'Masukkan nomor Virtual Account', 'Konfirmasi dan masukkan PIN'] },
    ],
  },
  {
    id: 'alfamart',
    name: 'Alfamart / Alfamidi',
    images: 'https://upload.wikimedia.org/wikipedia/commons/8/86/Alfamart_logo.svg',
    payment_id: 'ALFAMART',
    minimum_amount: 10000,
    maximum_amount: 2500000,
    fee: 5000,
    fee_percent: 0,
    type: 'convenience_store',
    status: 'active',
    group: 'Convenience Store',
    instructions: [
      { title: 'Pembayaran di Alfamart / Alfamidi', steps: ['Kunjungi kasir Alfamart atau Alfamidi terdekat', 'Beritahu kasir ingin membayar transaksi Feryshop / Merchant Kode Pembayaran', 'Tunjukkan Kode Pembayaran kepada kasir', 'Lakukan pembayaran dengan tunai atau non-tunai'] },
    ],
  },
];

export const seedSliders = [
  {
    id: 1,
    title: 'Top Up Mobile Legends Instant & Termurah',
    image: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=1200&auto=format&fit=crop',
    url: '/order/mobile-legends',
    isActive: true,
  },
  {
    id: 2,
    title: 'Diskon Spesial Valorant Points',
    image: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=1200&auto=format&fit=crop',
    url: '/order/valorant',
    isActive: true,
  },
];

export const seedArticles = [
  {
    id: 1,
    title: 'Cara Top Up Mobile Legends Aman dan Cepat di Feryshop',
    slug: 'cara-top-up-mobile-legends-aman-cepat',
    image: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=1200&auto=format&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=1200&auto=format&fit=crop',
    excerpt: 'Panduan memilih nominal diamond MLBB, mengisi User ID dan Zone ID, sampai pembayaran selesai tanpa salah kirim.',
    content: '<p>Top up Mobile Legends di Feryshop dibuat sederhana untuk pemain yang ingin proses cepat tanpa ribet. Siapkan User ID dan Zone ID, pilih nominal diamond atau Weekly Diamond Pass, lalu lanjutkan ke metode pembayaran yang tersedia.</p><p>Sebelum membayar, pastikan kembali detail akun dan nominal pesanan. Setelah pembayaran terverifikasi, sistem akan memproses pesanan secara otomatis sehingga diamond bisa masuk lebih cepat.</p><h2>Tips sebelum checkout</h2><ul><li>Salin User ID langsung dari profil game.</li><li>Pastikan Zone ID tidak tertukar dengan server lain.</li><li>Simpan invoice sampai pesanan selesai.</li></ul>',
    author: 'Admin Feryshop',
    views: 1840,
    created_at: '2026-07-20T10:00:00Z',
    published_at: '2026-07-20T10:00:00Z',
    category: { id: 1, title: 'Panduan', slug: 'panduan' },
  },
  {
    id: 2,
    title: 'Kenapa QRIS Jadi Metode Bayar Favorit Gamer?',
    slug: 'qris-metode-bayar-favorit-gamer',
    image: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?q=80&w=1200&auto=format&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?q=80&w=1200&auto=format&fit=crop',
    excerpt: 'QRIS praktis untuk top up karena bisa dipakai dari mobile banking dan e-wallet tanpa pindah-pindah channel pembayaran.',
    content: '<p>QRIS memudahkan pelanggan membayar pesanan dari berbagai aplikasi, mulai dari mobile banking sampai e-wallet. Untuk top up game, ini membantu proses checkout terasa lebih cepat karena pelanggan cukup memindai kode dan mengonfirmasi pembayaran.</p><p>Di Feryshop, QRIS cocok untuk transaksi harian seperti top up diamond, UC, atau voucher game. Pastikan nominal di aplikasi pembayaran sama dengan invoice sebelum konfirmasi.</p>',
    author: 'Tim Redaksi',
    views: 1125,
    created_at: '2026-07-21T08:30:00Z',
    published_at: '2026-07-21T08:30:00Z',
    category: { id: 2, title: 'Pembayaran', slug: 'pembayaran' },
  },
  {
    id: 3,
    title: 'Tips Membeli Akun Game agar Transaksi Lebih Aman',
    slug: 'tips-membeli-akun-game-aman',
    image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?q=80&w=1200&auto=format&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?q=80&w=1200&auto=format&fit=crop',
    excerpt: 'Periksa detail akun, metode pengamanan, dan bukti kepemilikan sebelum membeli akun game bernilai tinggi.',
    content: '<p>Membeli akun game membutuhkan kehati-hatian lebih dibanding top up biasa. Pelanggan perlu melihat detail akun, riwayat bind, skin atau item utama, serta status keamanan email dan nomor pemulihan.</p><p>Gunakan alur transaksi yang jelas dan hindari berpindah komunikasi ke channel yang tidak tercatat. Simpan bukti percakapan, invoice, dan detail pesanan sampai proses serah terima selesai.</p><h2>Checklist pembeli</h2><ul><li>Cek kecocokan item dengan deskripsi.</li><li>Pastikan email atau metode login bisa dipindahkan.</li><li>Jangan bagikan kode OTP kepada pihak lain.</li></ul>',
    author: 'Admin Feryshop',
    views: 2670,
    created_at: '2026-07-22T12:00:00Z',
    published_at: '2026-07-22T12:00:00Z',
    category: { id: 3, title: 'Marketplace', slug: 'marketplace' },
  },
  {
    id: 4,
    title: 'Update Promo Mingguan: Hemat untuk Top Up Favorit',
    slug: 'update-promo-mingguan-top-up-favorit',
    image: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?q=80&w=1200&auto=format&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?q=80&w=1200&auto=format&fit=crop',
    excerpt: 'Cek promo mingguan Feryshop untuk beberapa produk populer dan metode pembayaran tertentu.',
    content: '<p>Setiap minggu Feryshop menyiapkan promo berbeda untuk produk populer. Promo bisa berupa potongan harga, cashback terbatas, atau harga khusus untuk member tertentu.</p><p>Pastikan membaca periode promo dan syarat pembayaran sebelum checkout. Jika promo sudah berakhir, harga akan kembali mengikuti harga normal yang tampil di halaman produk.</p>',
    author: 'Tim Promo',
    views: 980,
    created_at: '2026-07-23T09:10:00Z',
    published_at: '2026-07-23T09:10:00Z',
    category: { id: 4, title: 'Promo', slug: 'promo' },
  },
  {
    id: 5,
    title: 'Panduan Top Up Valorant Points untuk Pemula',
    slug: 'panduan-top-up-valorant-points-pemula',
    image: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=1200&auto=format&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?q=80&w=1200&auto=format&fit=crop',
    excerpt: 'Kenali cara mengisi Riot ID dengan benar sebelum membeli Valorant Points.',
    content: '<p>Valorant Points digunakan untuk membeli skin, battle pass, dan item kosmetik lain di Valorant. Saat melakukan top up, pastikan Riot ID dan tag sudah benar karena keduanya dipakai untuk mengarahkan transaksi.</p><p>Jika ragu, buka profil Riot atau halaman akun untuk menyalin Riot ID. Hindari mengetik manual bila tag berisi karakter yang mudah tertukar.</p>',
    author: 'Tim Redaksi',
    views: 1430,
    created_at: '2026-07-24T11:45:00Z',
    published_at: '2026-07-24T11:45:00Z',
    category: { id: 1, title: 'Panduan', slug: 'panduan' },
  },
  {
    id: 6,
    title: 'Cara Mengecek Status Invoice Setelah Pembayaran',
    slug: 'cara-mengecek-status-invoice-setelah-pembayaran',
    image: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?q=80&w=1200&auto=format&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?q=80&w=1200&auto=format&fit=crop',
    excerpt: 'Gunakan halaman invoice untuk memantau pembayaran, proses pesanan, dan status transaksi sampai selesai.',
    content: '<p>Setelah checkout, pelanggan akan mendapatkan invoice sebagai pusat informasi transaksi. Di halaman invoice, pelanggan bisa melihat nominal pembayaran, metode yang dipilih, serta status pemrosesan pesanan.</p><p>Jika status belum berubah beberapa saat setelah pembayaran, tunggu proses sinkronisasi dari provider pembayaran. Simpan nomor invoice agar tim support dapat membantu pengecekan lebih cepat.</p>',
    author: 'Customer Care',
    views: 760,
    created_at: '2026-07-25T07:20:00Z',
    published_at: '2026-07-25T07:20:00Z',
    category: { id: 2, title: 'Pembayaran', slug: 'pembayaran' },
  },
  {
    id: 7,
    title: 'Tips Booyah Free Fire Solo Ranked Lebih Konsisten',
    slug: 'tips-booyah-free-fire-solo-ranked',
    image: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?q=80&w=1200&auto=format&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?q=80&w=1200&auto=format&fit=crop',
    excerpt: 'Atur rotasi, pilih senjata yang stabil, dan siapkan utility agar peluang Booyah lebih tinggi.',
    content: '<p>Bermain solo ranked di Free Fire menuntut keputusan cepat. Hindari turun di area terlalu ramai jika target utama adalah poin rank, lalu cari posisi aman untuk rotasi ke zona berikutnya.</p><p>Gunakan Gloo Wall dengan disiplin dan jangan memaksakan duel terbuka saat perlengkapan belum cukup. Diamond bisa digunakan untuk kebutuhan event atau item kosmetik, tetapi strategi tetap menjadi faktor utama.</p>',
    author: 'Gamer Pro',
    views: 2210,
    created_at: '2026-07-26T14:15:00Z',
    published_at: '2026-07-26T14:15:00Z',
    category: { id: 5, title: 'Tips Game', slug: 'tips-game' },
  },
  {
    id: 8,
    title: 'Perbedaan Member Biasa, Gold, dan Platinum di Feryshop',
    slug: 'perbedaan-member-biasa-gold-platinum-feryshop',
    image: 'https://images.unsplash.com/photo-1556742502-ec7c0e9f34b1?q=80&w=1200&auto=format&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1556742502-ec7c0e9f34b1?q=80&w=1200&auto=format&fit=crop',
    excerpt: 'Ketahui manfaat level member dan bagaimana harga khusus bisa membantu pelanggan aktif berhemat.',
    content: '<p>Level member membantu pelanggan aktif mendapatkan pengalaman belanja yang lebih baik. Perbedaan level dapat memengaruhi harga produk tertentu, akses promo, atau benefit khusus sesuai program yang sedang berjalan.</p><p>Pastikan login sebelum checkout agar sistem dapat membaca level akun dan menampilkan harga yang sesuai. Jika harga belum berubah, coba refresh halaman atau hubungi support dengan menyertakan email akun.</p>',
    author: 'Admin Feryshop',
    views: 905,
    created_at: '2026-07-27T10:40:00Z',
    published_at: '2026-07-27T10:40:00Z',
    category: { id: 6, title: 'Akun', slug: 'akun' },
  },
  {
    id: 9,
    title: 'Apa yang Harus Dilakukan Jika Pesanan Belum Masuk?',
    slug: 'pesanan-belum-masuk-apa-yang-harus-dilakukan',
    image: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?q=80&w=1200&auto=format&fit=crop',
    thumbnail: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?q=80&w=1200&auto=format&fit=crop',
    excerpt: 'Langkah pengecekan yang bisa dilakukan sebelum menghubungi support saat pesanan belum diterima.',
    content: '<p>Jika pesanan belum masuk, cek terlebih dahulu status invoice dan pastikan pembayaran sudah berhasil dari aplikasi pembayaran. Beberapa provider membutuhkan waktu sinkronisasi sebelum transaksi diteruskan ke sistem.</p><p>Siapkan nomor invoice, bukti pembayaran, dan data akun game saat menghubungi support. Informasi lengkap membantu tim melakukan pengecekan lebih cepat dan mengurangi risiko salah validasi.</p>',
    author: 'Customer Care',
    views: 1320,
    created_at: '2026-07-28T13:25:00Z',
    published_at: '2026-07-28T13:25:00Z',
    category: { id: 7, title: 'Bantuan', slug: 'bantuan' },
  },
];

export const seedSettings = {
  site_name: 'Feryshop',
  site_title: 'Feryshop - Marketplace Akun Game Sultan & Top Up',
  site_description: 'Platform marketplace akun game Sultan dan layanan top up game resmi termurah dan otomatis 24 jam di Indonesia.',
  logo: '/logo-2.png',
  favicon: '/favicon.ico',
  footer_text: 'Made in Feryshop',
  social_facebook: 'https://facebook.com',
  social_instagram: 'https://instagram.com',
  social_whatsapp: 'https://wa.me/628123456789',
};
